In [1]:
import h5py as h5
import numpy as np
import os
import matplotlib.pyplot as plt
from tqdm import tqdm
data_path = '/home/rfit/Telescope_Array/phd_work/data/normed/pr_q4_14yr_e1_0110_excl_sat_F_excl_geo_F.h5'

In [5]:
with h5.File(data_path,'r') as f:
    print('keys', list(f.keys()))
    train = f['test']
    print(list(train.keys()))
    print(train['ev_starts'][()])
    print(train['ev_ids'][()])
    print(train['dt_params'])
    
    norm_param = f['norm_param']['dt_params']
    norm_param_std = norm_param['std'][()]
    norm_param_mean = norm_param['mean'][()]
    ev_starts_data = train['ev_starts'][()] 
    dt_params_data = train['dt_params'][()]
    ev_ids_data = train['ev_ids'][()]
    dt_mask = train['dt_mask'][()]

keys ['norm_param', 'test', 'train', 'val']
['dt_bundle', 'dt_mask', 'dt_params', 'ev_ids', 'ev_starts', 'mc_params', 'recos', 'wfs_flat']
[       0       54       86 ... 12362704 12362748 12362787]
[[2.01406130e+07 2.38124167e+04 1.00000000e+00]
 [2.02204100e+07 2.14129791e+05 1.00000000e+00]
 [2.01101270e+07 2.02723611e+05 1.00000000e+00]
 ...
 [2.01308190e+07 1.12244816e+05 1.00000000e+00]
 [2.01202170e+07 2.50193128e+04 1.00000000e+00]
 [2.01001020e+07 1.25212122e+05 1.00000000e+00]]
<HDF5 dataset "dt_params": shape (12362787, 6), type "<f4">


In [6]:
data = []
for idx in tqdm(range(len(ev_starts_data)-1)):
    st = ev_starts_data[idx]
    fn = ev_starts_data[idx + 1]
    data.append(dt_params_data[st:fn])

100%|██████████| 499795/499795 [00:00<00:00, 1028753.56it/s]


In [8]:
cd ..

/home/rfit/Telescope_Array/phd_work


In [9]:
import src.train_VAE as VAE_dir

In [ ]:
model = VAE_dir.model.VAE()